# Generated by Django 3.1.7 on 2021-06-28 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_creation_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creation',
            name='content',
            field=models.TextField(verbose_name='conținut'),
        ),
        migrations.AlterField(
            model_name='creation',
            name='title',
            field=models.CharField(max_length=100, verbose_name='titlu'),
        ),
    ]
